version: '3.8'

services:
  db:
    image: postgres
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/dynatable:z
    environment:
      POSTGRES_DB: dynatable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  dynatable:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db


  test:
    build: .
    command: poetry run pytest src/
    volumes:
      - .:/src
    depends_on:
      - db


volumes:
  postgres_volume:
